name: now_in_dart_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  isar: 3.0.0-dev.14
  isar_flutter_libs: 3.0.0-dev.14
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  isar_generator: 3.0.0-dev.14
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
