name: now_in_dart_flutter
description: A simple app that uses WebView under the hood to display all the news and updates regarding Dart and Flutter. The information is retrieved using GitHub's API and the github repository used as source is that of Flutter and Dart's.

publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  equatable: ^2.0.5
  flash: ^3.0.5+1
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  meta: ^1.10.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  path_provider: ^2.1.1
  vector_graphics: ^1.1.9+1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2
  test: ^1.25.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
