name: now_in_dart_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flash: ^2.0.3+3
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  meta: ^1.9.1
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  isar_generator: ^3.1.0+1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
